### PR TITLE
Hide map title when it is blank

### PR DESCRIPTION
**Pull request by adrien-delhorme**
object.get_title() returns "Map" when the title is blank. Using object.title allows the user to have no title above the map.

### CODE REVIEW

**Comment by bittner** [comment]
The build on Travis is failing for tox having dropped Python 3.3. I'll update the CI configuration later, don't worry.

**Comment by adrien-delhorme** [comment]
Tested on
- Python 2.7.9
- Django 1.11.7
- Django CMS 3.4.6

**Comment by bittner** [comment]
Thank you for your contribution!

**Comment by bittner** [comment]
Version [0.9.0](https://pypi.org/project/djangocms-maps/) released with the changes, just now. :tada:

**Pull request merged**
